### PR TITLE
Update new languages in i18nextConfig.js

### PR DESCRIPTION
**Pull request by Mominarez**
fixed syntax error

### Checklist

- [x] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [x] I have listed my proposed changes and their benefits.
- [x] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Comment by XanderRubio** [comment]
Hi @Mominarez,

I appreciate your time and enthusiasm in working on the translations! 😇 I'd like to suggest a more efficient approach for both of us when contributing your changes. Instead of creating multiple pull requests for each translation or file modification, it's better to make all your changes on a single branch and then create just one pull request.

To do this, you can work on the same branch for all your translation updates and file edits. Once you've completed your work and are ready to submit it for review, go ahead and open a single pull request. This will make it easier for me to review all your changes in one place, streamlining the review process.

Thank you again for your contributions, and please feel free to reach out if you have any questions or need further clarification.

**Comment by Mominarez** [comment]
> Hi @Mominarez,
> 
> I appreciate your time and enthusiasm in working on the translations! 😇 I'd like to suggest a more efficient approach for both of us when contributing your changes. Instead of creating multiple pull requests for each translation or file modification, it's better to make all your changes on a single branch and then create just one pull request.
> 
> To do this, you can work on the same branch for all your translation updates and file edits. Once you've completed your work and are ready to submit it for review, go ahead and open a single pull request. This will make it easier for me to review all your changes in one place, streamlining the review process.
> 
> Thank you again for your contributions, and please feel free to reach out if you have any questions or need further clarification.

Hello @XanderRubio,

Thank you for letting me know about a more efficient approach in pull requests and I apologize for making it difficult to review them on your end. I will open a single pull request by today.

**Comment by XanderRubio** [comment]
> > Hi @Mominarez,
> > I appreciate your time and enthusiasm in working on the translations! 😇 I'd like to suggest a more efficient approach for both of us when contributing your changes. Instead of creating multiple pull requests for each translation or file modification, it's better to make all your changes on a single branch and then create just one pull request.
> > To do this, you can work on the same branch for all your translation updates and file edits. Once you've completed your work and are ready to submit it for review, go ahead and open a single pull request. This will make it easier for me to review all your changes in one place, streamlining the review process.
> > Thank you again for your contributions, and please feel free to reach out if you have any questions or need further clarification.
> 
> Hello @XanderRubio,
> 
> Thank you for letting me know about a more efficient approach in pull requests and I apologize for making it difficult to review them on your end. I will open a single pull request by today.

@Mominarez No need to apologize as open source, git, the world of software is a lifelong learning pursuit and we are all constantly learning new topics and workflow every day.

**Comment by Mominarez** [comment]
> > > Hi @Mominarez,
> > > I appreciate your time and enthusiasm in working on the translations! 😇 I'd like to suggest a more efficient approach for both of us when contributing your changes. Instead of creating multiple pull requests for each translation or file modification, it's better to make all your changes on a single branch and then create just one pull request.
> > > To do this, you can work on the same branch for all your translation updates and file edits. Once you've completed your work and are ready to submit it for review, go ahead and open a single pull request. This will make it easier for me to review all your changes in one place, streamlining the review process.
> > > Thank you again for your contributions, and please feel free to reach out if you have any questions or need further clarification.
> > 
> > 
> > Hello @XanderRubio,
> > Thank you for letting me know about a more efficient approach in pull requests and I apologize for making it difficult to review them on your end. I will open a single pull request by today.
> 
> @Mominarez No need to apologize as open source, git, the world of software is a lifelong learning pursuit and we are all constantly learning new topics and workflow every day.

Hello! I've been caught up with work so it looks like I wont be able to complete it this weekend as I thought I would, is it okay if I can finish this assignment on Wednesday? If not, I understand if you assign this task to someone else. Thank you!

**Comment by XanderRubio** [comment]
> > > > Hi @Mominarez,
> > > > I appreciate your time and enthusiasm in working on the translations! 😇 I'd like to suggest a more efficient approach for both of us when contributing your changes. Instead of creating multiple pull requests for each translation or file modification, it's better to make all your changes on a single branch and then create just one pull request.
> > > > To do this, you can work on the same branch for all your translation updates and file edits. Once you've completed your work and are ready to submit it for review, go ahead and open a single pull request. This will make it easier for me to review all your changes in one place, streamlining the review process.
> > > > Thank you again for your contributions, and please feel free to reach out if you have any questions or need further clarification.
> > > 
> > > 
> > > Hello @XanderRubio,
> > > Thank you for letting me know about a more efficient approach in pull requests and I apologize for making it difficult to review them on your end. I will open a single pull request by today.
> > 
> > 
> > @Mominarez No need to apologize as open source, git, the world of software is a lifelong learning pursuit and we are all constantly learning new topics and workflow every day.
> 
> Hello! I've been caught up with work so it looks like I wont be able to complete it this weekend as I thought I would, is it okay if I can finish this assignment on Wednesday? If not, I understand if you assign this task to someone else. Thank you!

Hi @Mominarez, I've updated task #76 to be due by the end of the day on Wednesday. Another contributor has expressed interest in working on the remaining parts of the issue, but since you've already invested time and effort into it, I don't want you to feel like your work has gone to waste. I hope you have a great start to your week!

**Comment by XanderRubio** [comment]
Hi @Mominarez,

I have informed the other contributor who was inquiring about the remaining language translations that they can start working on it now. Of course, you are always welcome to continue contributing to Before I Die Code whenever you want. Our goal is to make it a great place for developers to improve their skills. Have a wonderful rest of your week!

**Pull request closed without merging**
