### PR TITLE
Add Contributor Navigation Button and update label

### LINKED ISSUE #182: [Feature Request] Create button to direct to Contributor Page
### Description

Please create a button on the website's [main page](https://before-i-die-achievements.vercel.app/) to direct users to the [Contributor Page](https://before-i-die-achievements.vercel.app/contributors-map).

Ideally, place the Contributors Button Below the Contributors button and title it `CONTRIBUTORS MAP` and also rename the `CONTRIBUTORS` button to `CONTRIBUTORS LIST.` For now, please keep it the same style as the other buttons. Thank you!

### Screenshots

Please place the button here:
Screenshot 2023-10-12 at 00 25 46

It will direct you to this page:

Screenshot 2023-10-12 at 00 27 05

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by koleajeolayinka**
## Issue Addressed
Closes #182

### Checklist

- [x] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [ ] I have listed my proposed changes and their benefits.
- [x] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
Excellent @koleajeolayinka! Thank you for adding the button. Every small contribution continually assists in growing the project, and I am very grateful for your assistance. It looks great and functions correctly! We are going ahead with merging and will be adding more issues to this repo, and you are always free to add your own issues to improve the code.

**Comment by XanderRubio** [comment]
Successfully merged, and this closes out issue #182!

**Comment by koleajeolayinka** [comment]
Thank you so much for your kind words! I'm happy to hear that the small button addition is working well. I'm always eager to contribute to the project and look forward to tackling more issues. If there's anything specific you'd like me to focus on or if you have new issues in mind, please let me know. I'm excited about the continued growth of the project 💡

**Comment by XanderRubio** [comment]
Great! Please tell me if you have any ideas of features you are very interested in working on with new tech stacks or skills you want to apply for work experience to this repo, and we can figure out an issue to create that adds value to the project, and you learn in the process. Let me know! Have a look at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md). It is a little outdated but has ideas to get you thinking.

**Comment by koleajeolayinka** [comment]
> Great! Please tell me if you have any ideas of features you are very interested in working on with new tech stacks or skills you want to apply for work experience to this repo, and we can figure out an issue to create that adds value to the project, and you learn in the process. Let me know! Have a look at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md). It is a little outdated but has ideas to get you thinking.

I'm mainly into front-end technologies. I'll check out the ROADMAP and suggest ideas that align with my skills. Looking forward to contributing!  👩‍🔧

**Pull request merged**
