### PR TITLE
'Feature'  / Closes #45

### LINKED ISSUE #45: 🟢 Clarify instructions for dummy images in contribution guidelines, enhance design 🎨
**Problem**🤔

Contributor @ccelest1 pointed out that the [contribution guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) do not provide clear instructions for [dummy_images](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/public/img/dummy_image). For example there role and purpose. We should update the [contribution guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) to provide clearer instructions for what is the purpose of the [dummy_images](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/public/img/dummy_image). This led us to think about expanding in the [Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) what the dummy_images are and additionally, we can work on adding a section in the files to have users add high-quality images of dummy images to be later displayed on rotation when a user is viewing the website. 

Current view of the static dummy images on the home page⬇️
Screenshot 2023-08-30 at 16 31 43

**Task**⛏️🪚🔨
(https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/feature-dummy_image)
- [ ] Will need to define what the design of the dynamic [dummy_images](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/public/img/dummy_image) looks best on the home page. Currently there are ten images displayed 
- [ ]  Add into the [contribution guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) the purpose of the dummy_images and how user submit them, the image quality, image standards 
- [ ] Develop the ability to have [dummy_images](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/public/img/dummy_image) display on rotation. This will need to be done in the [BrickLayout](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/BrickLayout/BrickLayout.jsx) file. 

### 🌲 Please work on this issue on the branch [feature-dummy_image]
** IF NEEDED, WE CAN CREATE INDIVIDUAL ISSUES FOR EACH OF THE TASKS ABOVE 

### Please see the two code examples below ⬇️ for ideas on how to address the BrickLayout Component

1️⃣ To allow contributors to upload dummy images to your open source project and display 9 images at a time (as an example) in a randomized manner, you can modify the BrickLayout component as follows:

1. Pass the images uploaded by contributors as props to the BrickLayout component.
2. Use the useState hook to store the shuffled array of images.
3. Use the useEffect hook to shuffle the array of images whenever it changes.
4. Use the slice method to display only 9 images at a time.
5. Use the setInterval method to rotate the displayed images after a certain interval.

```
import React, { useState, useEffect } from "react";
import styles from "./BrickLayout.module.css";

const BrickLayout = ({ images }) => {
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentIndex((currentIndex + 1) % images.length);
    }, getRandomInt(5000, 10000));
    return () => clearInterval(intervalId);
  }, [currentIndex, images]);

  const displayedImages = images.slice(currentIndex, currentIndex + 9);

  return (
    <div>
      <div className={styles["blur-circle-shape-two"]}></div>
      <div className={styles["brick-layout"]}>
        <div className={styles["brick-column"]}>
          {displayedImages.map((image, index) => (
            <img key={index} src={image} alt="" />
          ))}
        </div>
      </div>
    </div>
  );
};

export default BrickLayout;

// Function to get a random integer between min and max
const getRandomInt = (min, max) => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};
```

2️⃣ To make each image disappear and then reappear with another image in its place in different time sequences between 5-10 second intervals, you can modify the BrickLayout component as follows:

1. Pass the images uploaded by contributors as props to the BrickLayout component.
2. Use the useState hook to store the index of the current image.
3. Use the useEffect hook to change the index of the current image after a certain interval.
4. Use the setInterval method to change the index of the current image after a certain interval.
5. Use the slice method to display only 9 images at a time.

```
import React, { useState, useEffect } from "react";
import styles from "./BrickLayout.module.css";

const BrickLayout = ({ images }) => {
  const [currentIndex, setCurrentIndex] = useState(0);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setCurrentIndex((currentIndex + 1) % images.length);
    }, getRandomInt(5000, 10000));
    return () => clearInterval(intervalId);
  }, [currentIndex, images]);

  const displayedImages = images.slice(currentIndex, currentIndex + 9);

  return (
    <div>
      <div className={styles["blur-circle-shape-two"]}></div>
      <div className={styles["brick-layout"]}>
        <div className={styles["brick-column"]}>
          {displayedImages.map((image, index) => (
            <img key={index} src={image} alt="" />
          ))}
        </div>
      </div>
    </div>
  );
};

export default BrickLayout;

// Function to get a random integer between min and max
const getRandomInt = (min, max) => {
  return Math.floor(Math.random() * (max - min + 1)) + min;
};
```

**Resources**
[🪟 Image Grid / Masonry Layout for React](https://github.com/prabhuignoto/react-visual-grid)
[React Visual Grid Docs](https://react-visual-grid.prabhumurthy.com/)
Image from the React Visual Grid that could be used as the layout for the dummy image backdrop⬇️
Screenshot 2023-08-30 at 16 43 09

### PR DESCRIPTION
**Pull request by negar-75**
## Issue Addressed

Closes #45

## Proposed Changes and Benefits

I created another design of header to make it more dynamic ,
it is not a final version , It is like a preview

## Screenshots

Screenshot 2023-09-20 091709
Screenshot 2023-09-20 091715

## Notes to Reviewers

we have to make a way to put another things you want to have in header

### CODE REVIEW

**Comment by XanderRubio** [comment]
WOW! 

I am impressed by the animation of the images and the dynamic color changes. The project is progressing well, and we can further refine the text order, select sharper images for better clarity when enlarged or displayed in full screen, and determine the placement of the GitHub repository link. My initial impressions are positive, as the creativity and uniqueness of the project are evident upon first viewing the site. From my perspective, the goal is to achieve a professional and creative appearance for the initial part of the site.

I see there have been numerous updates and a few more design modifications to the [MasonryBox.jsx](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryBox/MasonryBox.jsx) are yet to be reflected from the main. However, I am confident that we can merge these changes without any conflicts, as they pertain to a section of the code unrelated to the MasonryLayout component later on when we arrive at a finished version for your contribution. 

We should consider how to present the GitHub repository link or button, as many open-source projects also include a link to "star" the repository, which helps attract attention on GitHub. Upon reviewing your draft for the third time, I appreciate the added effect for the opening and closing of the image presentation. We should be able to update the color scheme to match the blue and yellow branding of the logo. Do you think it would be beneficial to incorporate the logo somewhere?

Additionally, I want to add that we are not considering making this highly accessible to all users for the time being (this can be a much later issue we address in the long term future) and more focusing on making this look creative, the wow effect and professional. 

Let's start first by changing the text displayed. 
An Open Source Project (always displayed as I always want people to know that this is an open source project and open to contribute to collaborate)
Then add the following text each time an image is displayed. 

1. 'to plant seeds 🌱 of inspiration.',
2. 'to codify 💻 your purpose.',
3. 'to compile your bucket 🪣 list.'
4. 'to learn how to contribute 📚.'
5. 'to learn new skills🎯.'
6. `to advance your career💼.

And then let's change the photos we are using. 

I'll help and want to get your feedback before we start working on this and future reference, we can collaborate via screen share if it helps too! Great work thus far, as I appreciate the time you have put into this feature.

**Comment by XanderRubio** [comment]
Ahh, and I wanted to mention we can go add and merge this into the feature branch of [BeforeIDieCode:feature-dummy_image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/feature-dummy_image) and to not make it so overwhelming create smaller areas we want to improve on as smaller issue/tasks to help with us staying organized and then it is also smaller changes we are adding every time for a new pull request. How does this sound? @negar-75

**Comment by negar-75** [comment]
so you want An Open Source Project always display
I think if the header is not fullscreen, the animation does not look good.
so like split the header section for animation and another for "An Open Source Project" is not a good idea, it does not look good,
so if I want to put "An Open Source Project" on the animation with absolute position I do not know it will look good !
so what do you think about that?

**Comment by XanderRubio** [comment]
> so you want An Open Source Project always display I think if the header is not fullscreen, the animation does not look good. so like split the header section for animation and another for "An Open Source Project" is not a good idea, it does not look good, so if I want to put "An Open Source Project" on the animation with absolute position I do not know it will look good ! so what do you think about that?

Good to note that the header isn't full screen, so the animation won't look good. I didn't do a good job in sharing my thoughts 😇 and I would agree that splitting the header section isn't a good idea that will make the animation not look as appealing. The more I think it makes sense for the order of text to be displayed to be first as `An Open Source Project` then the shutter slide image changes to show only
`plant seeds 🌱 of inspiration`
the shutter slide image changes to show 
`to codify 💻 your purpose`
the shutter slide image changes to show 
`to compile your bucket 🪣 list`
the shutter slide image changes to show 
`to learn how to contribute 📚`
the shutter slide image changes to show 
`to learn new skills🎯`
the shutter slide image changes to show 
`to advance your career💼`


This would be text on seven images that would be displayed now. 

I'll see about getting this to work on my local development to work to share in helping share my idea for this thought better 😀

And good you mentioned that the absolute positioning won't look good. By the way this type of image shows up great and I like how it looks with the shutter animation you have added. I like the [Mefikademo.ttf](https://github.com/BeforeIDieCode/BeforeIDieAchievements/pull/99/files#diff-8fc0c7f59a7c2e021cb4bbea445acb29de74e21393c7d381a318f38e4045c115) font that shows up that you have added. 

Screenshot 2023-09-20 at 17 10 09

**Comment by negar-75** [comment]
ok @XanderRubio 
let me play a game with design and see what is the best 😂😂😂

**Comment by XanderRubio** [comment]
> ok @XanderRubio let me play a game with design and see what is the best 😂😂😂

Great! Thank you for your patience in helping to understand what I am thinking also 😄

**Comment by negar-75** [comment]
Screenshot 2023-09-20 162716

if I want to split the header it would be something like this,
it is not that bad

**Comment by XanderRubio** [comment]
> Screenshot 2023-09-20 162716
> 
> if I want to split the header it would be something like this, it is not that bad

Agreed not bad. I would be in favor of not splitting the header as you had it before. It looks better if it is completely wide and would be easier to manage and work with for now.

**Comment by XanderRubio** [comment]
Hahaha, it's a bit more complex for me to get up and running on my local dev server, 😅 and wow! This is a more intensive design, especially after reviewing the Header.scss file. Great job on getting the version working, as there are lots of moving parts! 

I installed `npm install i18next react-i18next axios sass` and not sure if I missed a package to avoid this error. 

Screenshot 2023-09-20 at 23 30 39

**Comment by negar-75** [comment]
https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/113235504/e2c7c20e-2882-4d11-856f-788277242e68


take a look at this
i did some svg drawing like a handwriting
but there is a little bug 
can you see?

**Comment by negar-75** [comment]
there is still a dot before drawing started

**Comment by XanderRubio** [comment]
> bandicam-2023-09-21-18-21-24-559_OXxpd2sN.mp4 
> take a look at this i did some svg drawing like a handwriting but there is a little bug can you see?

Very neat, and I like the handwriting effect! You are going deep into the customization, and I appreciate your time in figuring it out and learning along the way😇. Hmm okay very weird why the `.` where it goes above the `j` is showing before the word `project` is being displayed and early too on a line above also from where it gets written on the right side of the spilt header.

**Comment by negar-75** [comment]
this is because of the "r" in "source",
could you work on this?
I did a lot of changes but nothing happened

**Comment by negar-75** [comment]
but this is just a sample,
we can use your logo there and use this effect for "Before I die" under the "an open source project"

**Comment by XanderRubio** [comment]
> this is because of the "r" in "source", could you work on this? I did a lot of changes but nothing happened

Certainly, I can take a look at this within the next few hours. Please recommit `git push` to the branch you're working on. Afterwards, I will clone it and examine the new i svg drawing/handwriting you've included on my local server.

**Comment by XanderRubio** [comment]
> but this is just a sample, we can use your logo there and use this effect for "Before I die" under the "an open source project"

Understood!

**Comment by negar-75** [comment]
https://github.com/BeforeIDieCode/BeforeIDieAchievements/assets/113235504/9e165304-7677-4796-bd60-a667c5398fcf

**Comment by negar-75** [comment]
this is another way to design
which one do you think is best?

**Comment by negar-75** [comment]
for emojis we have to use another one because they does not look good on pictures

**Comment by XanderRubio** [comment]
> this is another way to design which one do you think is best?

I like what you did with this version and going with the svg text as already there instead of the handwriting animation to solve the bug for now. As this is something we could come back to in the future. Looks great as this is starting to take shape now and your order you displayed the text over every image.

**Comment by negar-75** [comment]
so we can go for second version ! static and without drawing animation

**Comment by XanderRubio** [comment]
> for emojis we have to use another one because they does not look good on pictures

I agree that this issue often occurs when we install and use different fonts. To solve this problem, I suggest using websites like [openemoji](https://openmoji.org/) to find a matching emoji. Additionally, you may want to try using the [animated fluent emoji library](https://animated-fluent-emoji.vercel.app/). This involves copying and pasting the code next to the text being displayed instead of uploading a new SVG image, which may help ensure that the emojis display correctly.

**Comment by XanderRubio** [comment]
> so we can go for second version ! static and without drawing animation

Yes, for now, the animation can be another design feature and I don't want you spending more time as I know you've invested lots of time already into the new header and this can be a new addition in the future. The second version it is!

**Pull request closed without merging**
