### PR TITLE
Translated CONTRIBUTION-GUIDELINES.md into Hindi

### PR DESCRIPTION
**Pull request by abhinaba-dash**
translate CODE_OF_CONDUCT.md to hindi

Closes [3rd of 5] #30 issue 

## Issue Addressed
Closes [3rd of 5] #30 issue 

## Proposed Changes and Benefits

Added Hindi translation of CONTRIBUTION-GUIDELINES.md

### Checklist

- [x] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [x] I have listed my proposed changes and their benefits.
- [x] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Comment by abhinaba-dash** [comment]
Hello @XanderRubio please accept my PR.
And kindly add hacktoberfest label to the same.

**Comment by XanderRubio** [comment]
Hi @abhinaba-dash! 

Thank you for taking the time to contribute to Before I Die Code! I am currently traveling, and once I get situated in my next location I will review your pull request and if all is good merge right away. Have a nice day!

Xander

**Comment by XanderRubio** [comment]
> Hello @XanderRubio please accept my PR. And kindly add hacktoberfest label to the same.

What did you mean the label to be `hacktoberfest`? For this issue or pull request?

**Review by XanderRubio — APPROVED** [review]
Excellent @abhinaba-dash! Looks great, and the CONTRIBUTION-GUIDELINES is the longest to translating bravo! Thank you for contributing your time and helping this open-source project become more accessible. Going ahead with merging now!

**Comment by XanderRubio** [comment]
This pull request adds to issue #30 and is missing only one more task to be completed.

**Comment by XanderRubio** [comment]
Congratulations, @abhinaba-dash, for your pull request being merged! I would recommend you add your text and image to represent what you want to do before you die in this repo. Then, you can become a member of the [Before I Die organization](https://github.com/BeforeIDieCode?view_as=public) additionally. Have a great day!

**Pull request merged**
