### PR TITLE
Docs: added translations for "before I die" in various languages.

### LINKED ISSUE #76: Expand Language Support for "Before I Die" Based on User's IP Address
**Description:** This issue aims to enhance the "Before I Die Code" project by adding more translations for the text "Before I Die" based on the user's IP address. We currently have six languages in the [locales](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/locales) folder, and we're using [react-i18next](https://www.perplexity.ai/react-i18next) for translations. Every time a pull request is closed, this list will be updated with the languages that have been added by contributors:

The following list represents the languages that are still missing and need a translation.json file added to our open-source code:
- [x] nl - Dutch
- [x] sv - Swedish
- [x] no - Norwegian
- [x] da - Danish
- [x] fi - Finnish
- [x] ru - Russian
- [x] zh - Chinese
- [x] ja - Japanese
- [x] hi - Hindi
- [x] ko - Korean
- [x] ms - Malay
- [x] id - Indonesian
- [x] tl - Tagalog
- [x] th - Thai
- [x] vi - Vietnamese
- [x] tr - Turkish
- [x] el - Greek
- [x] he - Hebrew 
- [x] ar - Arabic - added by contributor @sherikovic 
- [x] af - Afrikaans
- [x] sw - Swahili
- [x] pl - Polish
- [x] ro - Romanian
- [x] bg - Bulgarian
- [x] uk - Ukrainian
- [x] cs - Czech
- [x] sk - Slovak
- [x] hu - Hungarian
- [x] sl - Slovenian
- [x] hr - Croatian
- [x] sr - Serbian
- [x] bs - Bosnian
- [x] mk - Macedonian
- [x] sq - Albanian
- [x] lt - Lithuanian
- [x] lv - Latvian
- [x] et - Estonian
- [x] is - Icelandic
- [x] fa - Persian 
- [x] ur - Urdu 
- [x] ps - Pashto 
- [x] bn - Bengali
- [x] ne - Nepali
- [x] si - Sinhalese
- [x] my - Burmese
- [x] km - Khmer
- [x] lo - Lao
- [x] mn - Mongolian
- [x] dz - Dzongkha
- [x] kk - Kazakh
- [x] uz - Uzbek
- [x] ky - Kyrgyz
- [x] tg - Tajik
- [x] tk - Turkmen
- [x] ka - Georgian 
- [x] hy - Armenian 
- [x] az - Azerbaijani 
**Steps to complete this issue:**

1. Translate the text "Before I Die" into additional languages. This text is displayed when clicking on a contributor bid image ⬇️
Screenshot 2023-09-13 at 00 44 22

2. Create a JSON file for each new translation, following the format:
```
{
  "BEFORE-I-DIE": "Translation in the target language"
}
```
3. Add the new language JSON files to the [locales](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/src/locales) folder. Be sure to title this file `translation.json`
4. Update the [i18n configuration](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/i18nextConfig.js) to include the new languages. In the i18n configuration code, add the new language resources by importing the JSON files and including them in the resources object. For example:
```
import i18n from "i18next";
import { initReactI18next } from "react-i18next";

i18n
  .use(initReactI18next) // passes i18n down to react-i18next
  .init({
    resources: {
      en: {
        translation: require("./locales/en/translation.json"),
      },
      // Add new languages here
      newLanguageCode: {
        translation: require("./locales/newLanguageCode/translation.json"),
      },
    },
    lng: "en", // Set the default language
    fallbackLng: "en", // Fallback language if a translation is missing
    interpolation: {
      escapeValue: false, // React already escapes by default
    },
    returnNull: false,
  });
```

### PR DESCRIPTION
**Pull request by MeetThakur**
## Issue Addressed
Closes #76 

## Proposed Changes and Benefits
added new language support for all the required languages except the middle eastern languages for "Before I Die".

## Notes to Reviewers
I tried my best and kept the translation as error free as possible.
### Checklist

- [✔ ] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [✔  ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [ ✔ ] I have listed my proposed changes and their benefits.
- [✔  ] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
Great job, @VoidyCodes! Thank you for adding the 49 language files and updating the i18nextConfig.js file
. I have updated issue #76 with the list of completed languages and those still missing. If the current contributor doesn't finish them by the end of the week, we would appreciate your help in completing them. I will merge your changes now. Please make sure to add yourself to the [CONTRIBUTORS.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTORS.md) file and include your own "Before I Die" statement.

Does the `Before I Die` text change for you to Hindi from your IP address? As I see your profile you are in India. 

Have a great day!

**Comment by XanderRubio** [comment]
This merge updates 49 tasks for the issue #76

**Comment by MeetThakur** [comment]
I would gladly translate the other languages too if needed and I'll make sure to add myself in CONTRIBUTORS.md and include my before I die statement too.

and yes, it shows the before I die text in Hindi for me.

**Comment by XanderRubio** [comment]
> I would gladly translate the other languages too if needed and I'll make sure to add myself in CONTRIBUTORS.md and include my before I die statement too.
> 
> and yes, it shows the before I die text in Hindi for me.

Great @VoidyCodes and excellent to get confirmation on the `Before I Die` text showing in Hindi from your IP address. Look forward to seeing your next contribution!

**Pull request merged**
