### PR TITLE
add Kenneth Quiggins to Before I Die

### PR DESCRIPTION
**Pull request by KQuiggins**
I am adding Kenneth Quiggins to Before I Die with images and text

### CODE REVIEW

**Comment by XanderRubio** [comment]
Hi Ken! Thank you for taking the time to contribute and share your image and text. It says a lot about where your time, energy, and focus are for this moment in life to lead you to a life of flexibility and being able to contribute to your family! I hope your meetup with Code Louisville is productive. Please let me know from your experience and perspective your ideas to enhance the project from the [open issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues), [Roadmap](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) and your ideas. Have a great day! Keep growing and disciplined daily to make a life flexible and impactful to your family! Merging now, and your text and image look great on the Before I Die Code website!

**Comment by XanderRubio** [comment]
And to explain the additional commits I made on your pull request, I had to do two more commits to resolve merge conflicts that resulted from a previous contributor.

**Comment by KQuiggins** [comment]
Thank You! The project is great and I had a lot of fun adding to this project 😎

**Comment by XanderRubio** [comment]
Wonderful! The project will continue to grow, so whenever you have free time and want to contribute, it will still be expanding!

**Pull request merged**
