### PR TITLE
Add Sherif Amer to Before I Die

### PR DESCRIPTION
**Pull request by sherikovic**
Adding Sherif Amer's info to Before I Die

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
@sherikovic Great work and your image and text are great on the site! It is funny to note that the previous contributor before you had added a similar image of a van and mentioned that they also want to travel across the states. This is a great activity and experience because of the diverse topography of the United States and the road network in the US for traveling to and through National Parks and easily camp there in a van. Thank you for taking the time to contribute and share, Sherif! Going ahead with merging now.

**Comment by XanderRubio** [comment]
@sherikovic Your pull request has been successfully merged!!! Congratulations Bottle with Popping CorkBottle with Popping CorkBottle with Popping CorkDouble Exclamation MarkDouble Exclamation MarkDouble Exclamation Mark

If you haven't already, please go ahead and star Glowing StarGlowing StarGlowing Starthis repo and you are more than welcome to continually contribute to this project by assisting with our [open issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues), or adding your own new open issues, and additionally you can get an idea of ideas we have to continually grow this project further as technology and tech stack continually evolve by looking at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) for the project. Have a great day, and thank you for taking the time to contribute, Sherif! You can view your contribution now on the [live link](https://before-i-die-achievements.vercel.app/). I am looking forward to your contribution to the location map feature. 

Xander

**Comment by sherikovic** [comment]
> @sherikovic Great work and your image and text are great on the site! It is funny to note that the previous contributor before you had added a similar image of a van and mentioned that they also want to travel across the states. This is a great activity and experience because of the diverse topography of the United States and the road network in the US for traveling to and through National Parks and easily camp there in a van. Thank you for taking the time to contribute and share, Sherif! Going ahead with merging now.

Oh I honestly didn't see that at all lol, I'm glad I'm not the only one that shares this. And I agree, it should be amazing!

**Comment by XanderRubio** [comment]
> > @sherikovic Great work and your image and text are great on the site! It is funny to note that the previous contributor before you had added a similar image of a van and mentioned that they also want to travel across the states. This is a great activity and experience because of the diverse topography of the United States and the road network in the US for traveling to and through National Parks and easily camp there in a van. Thank you for taking the time to contribute and share, Sherif! Going ahead with merging now.
> 
> 
> 
> Oh I honestly didn't see that at all lol, I'm glad I'm not the only one that shares this. And I agree, it should be amazing!

Make it happen!

**Pull request merged**
