### PR TITLE
feat: adding templates for issues

### LINKED ISSUE #92: Issue and Pull Request Templates
## Problem
I noticed that this repository is missing templates for PRs and Issues. 
## Disadvantage 
This can make it difficult for people who are very new to open source to have difficulty with sharing their contribution ideas and submit them.

## Possible Solution
Create Issue templates for specific issues like Documentation, Bugs, Feature requests, Security, etc.
- See this example
```
name: General Issue
description: This template can be used for any type of issue, including bug reports, feature requests, and questions.
labels: ["general"]

body:
  ---
  **Title:** Describe your issue in a clear and concise title.
  **Description:** Provide a detailed description of your issue, including steps to reproduce it and any relevant error messages.
  **Environment:** Include information about your environment, such as the operating system, browser version, and any relevant software versions.
  **Attachments:** If possible, attach any screenshots, screen recordings, or other files that may help to diagnose the issue.
  ---

```
 For pull request templates, you can add comments on how to link issues that are addressed in the PRs, how to show the solution, and specific steps needed to ensure that contributors are submitting their PRs properly. 
 
Here's an example:

```
# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
```
## Benefits
This would help new contributors develop good writing habits when raising an issue and filling out a PR form. For maintainers, these tools would help them review these requests and determine if they align with the project's purpose.

### PR DESCRIPTION
**Pull request by CBID2**
## Description
This PR adds templates for and issues 

## Benefits 
This will help new contributors effectively raise issues and submit their pull requests to the project. 
## Related Issue
Closes #92 

## Note to Reviewers
This is still a work in progress

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
Great work once again @CBID2! I love this addionon of having the pr templatres and I have noticed many open source projects with high engagement or collaboration have this feature. This is a great start and you have built a foundation that we can continually expand on with more templates for example: 
- Performance improvement: An issue template for suggesting performance enhancements to the existing codebase.
- Code quality improvement: An issue template for proposing code refactoring or improvements to coding practices.
- Design/UX improvement: An issue template for suggesting improvements to the user interface or user experience of the project.
- Question/Help: An issue template for users who have questions or need help with the project.
- External contribution: A pull request template specifically for external contributors, outlining the process and requirements for submitting a pull request.
- Standard pull request template: A general pull request template that includes steps to follow before submitting a PR, such as ensuring the PR is not a duplicate, creating a descriptive commit message, and working in a separate branch with a descriptive name.

This can be another new issue for contributors to work on with the ever growing templates we have for contribution. 

**Good with going ahead with making this an open issue and merging!**

**Comment by XanderRubio** [comment]
Thank you @CBID2 for your enthusiasm regarding the templates and for taking the time to provide detailed yaml files. Greatly appreciate it!

**Comment by XanderRubio** [comment]
This pull request successfully closes out issue #92 from contributor @CBID2 ✅

**Comment by CBID2** [comment]
> Thank you @CBID2 for your enthusiasm regarding the templates and for taking the time to provide detailed yaml files. Greatly appreciate it!

Thanks for your enthusiasm @XanderRubio! Just a note for future reference, when someone has a PR in draft mode, don't merge it yet. It means that they need to add more code/commits.

**Comment by XanderRubio** [comment]
> > Thank you @CBID2 for your enthusiasm regarding the templates and for taking the time to provide detailed yaml files. Greatly appreciate it!
> 
> Thanks for your enthusiasm @XanderRubio! Just a note for future reference, when someone has a PR in draft mode, don't merge it yet. It means that they need to add more code/commits.

Thank you for your assistance and for helping me improve efficiency in handling a PR in draft mode. 😎

**Comment by CBID2** [comment]
> > > Thank you @CBID2 for your enthusiasm regarding the templates and for taking the time to provide detailed yaml files. Greatly appreciate it!
> 
> > 
> 
> > Thanks for your enthusiasm @XanderRubio! Just a note for future reference, when someone has a PR in draft mode, don't merge it yet. It means that they need to add more code/commits.
> 
> 
> 
> Thank you for your assistance and for helping me improve efficiency in handling a PR in draft mode. 😎

You're welcome @XanderRubio! :) I mentioned this in a DM to you on LinkedIn but I'll share it here too. Can I reopen this issue, and your suggestions to my form, and make a PR for the PR template? 😊

**Comment by XanderRubio** [comment]
> > > > Thank you @CBID2 for your enthusiasm regarding the templates and for taking the time to provide detailed yaml files. Greatly appreciate it!
> > 
> > 
> > > 
> > 
> > 
> > > Thanks for your enthusiasm @XanderRubio! Just a note for future reference, when someone has a PR in draft mode, don't merge it yet. It means that they need to add more code/commits.
> > 
> > 
> > Thank you for your assistance and for helping me improve efficiency in handling a PR in draft mode. 😎
> 
> You're welcome @XanderRubio! :) I mentioned this in a DM to you on LinkedIn but I'll share it here too. Can I reopen this issue, and your suggestions to my form, and make a PR for the PR template? 😊

Of course and this makes sense. I got ahead of myself and merged right away 😅

**Pull request merged**
