### PR TITLE
Feature: Implemented styles for the RandomContributor component

### PR DESCRIPTION
**Pull request by Angeltheesoto**
Created styles that best match the overall theme of the website. I placed the RandomContributor component below the github link as I felt that was the best location for it. When you hover over the container it also changes the background color to yellow like it does for the github link.

Screenshot 2023-09-15 175448

### CODE REVIEW

**Comment by XanderRubio** [comment]
Hi @Angeltheesoto! Did I miss your comment from last week on this issue? I thought I wrote feedback after reading this pull request last week. My apologies if I missed it. I hope you are well.

**Comment by Angeltheesoto** [comment]
Hi @XanderRubio, no worries and yea I wasn't sure if my request was sent or not as I'm still trying to familiarize myself with sending pull requests. I did want to ask, when I try and create a pull request using my own forked repo should I create a pull request using my forked "main" branch or my secondary branch name, such as "angel-soto-branch", because I know I'm never suppose to work on the main branch unless your pushing final code.

**Comment by XanderRubio** [comment]
> Hi @XanderRubio, no worries and yea I wasn't sure if my request was sent or not as I'm still trying to familiarize myself with sending pull requests. I did want to ask, when I try and create a pull request using my own forked repo should I create a pull request using my forked "main" branch or my secondary branch name, such as "angel-soto-branch", because I know I'm never suppose to work on the main branch unless your pushing final code.

Funny I really thought I wrote back to you last week. My apologies. It is important to work off the most up-to-date version of the main repo before creating a new feature branch. To do this, you should first perform a `git fetch` and then create your working branch from there. Once you've made your edits, add, commit, and push your changes. From there, you can create a pull request for your feature branch to be merged with the main branch. 

You are correct in the best practice for using `angel-soto-branch` as when you create a pull request it hels with ensuring that any changes made during the development process do not affect the main branch of Before I Die Code, allowing us to return to a stable state if needed. Does that help?

**Comment by Angeltheesoto** [comment]
@XanderRubio, Yes, thank you that really helped me understand it better. Also I made sure to pull the most up to date version of 'BeforeIDie' code before I created the pull request. At least I believe so, I first went to my cloned repo and it notified me to 'sync' the code which I did and then I pulled it into my local code and then pushed it and created the pull request. Please do let me know tho if I missed something or did something incorrectly.

**Comment by XanderRubio** [comment]
> @XanderRubio, Yes, thank you that really helped me understand it better. Also I made sure to pull the most up to date version of 'BeforeIDie' code before I created the pull request. At least I believe so, I first went to my cloned repo and it notified me to 'sync' the code which I did and then I pulled it into my local code and then pushed it and created the pull request. Please do let me know tho if I missed something or did something incorrectly.

Nice! You did great, and those are the correct steps many times when you are able to work within GitHub to make updates to your cloned repo it can be a little easier to work with than doing everything from the command line in the terminal. You were correct and keep on building upon it! Have a great weekend @Angeltheesoto

**Pull request closed without merging**
