### PR TITLE
change "Made" in footer with brackets w typing

### PR DESCRIPTION
**Pull request by samejima-san**
## Issue Addressed
this push addresses issue #159

## Proposed Changes and Benefits
it replaces the word "Made" in the footer with a code icon that when the user hovers over the icon plays typing sounds and stops once the user stops

### Checklist

- [x] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [x] I have listed my proposed changes and their benefits.
- [x] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Comment by XanderRubio** [comment]
Hi @samejima-san! Thank you for your prompt work on the UI enhancement to the footer. The functionality and appearance are impressive. The typing sound operates smoothly with the on and off mouse hovering. Please, for future reference, please ensure that you only work on open issues after they have been assigned to you. This helps maintain good organizational practices and prevents multiple contributors from working on the same issue simultaneously.

I'm mentioning this because other open source projects typically operate this way, and another contributor has already been assigned to work on this issue. Since you've put effort into this task, I will merge your work into the main branch for now, so you receive credit for a merged pull request. Once the other contributor finishes their work and submits a merge request, I will merge their work as well, since they were originally assigned to the task.

Does that make sense? We appreciate your enthusiasm and contributions to the project, and you're always welcome to participate. Feel free to create your own open issues to suggest improvements to the code! 😇

**Review by XanderRubio — APPROVED** [review]

**Comment by XanderRubio** [comment]
Thank you @samejima-san for your addition! This is a temporary enhancement to issue #159, as this issue belongs to contributor @tushar1-000 and will be merged from their pull request later.

**Comment by samejima-san** [comment]
@XanderRubio Sorry, I already mentally started working on this before anyone commented on the issue.

**Comment by XanderRubio** [comment]
@samejima-san All good and I appreciate you taking initiative right away to work on the issue 😉

**Pull request merged**
