### PR TITLE
Add Ma'aruf Muhammad to Before I Die

### PR DESCRIPTION
**Pull request by Rockleemode**
Add images and text to Before I Die

### CODE REVIEW

**Comment by Rockleemode** [comment]
@XanderRubio I have pushed the code

**Comment by XanderRubio** [comment]
> @XanderRubio I have pushed the code

Hey @Rockleemode! I want to thank you for your prompt attention and assistance. Unfortunately, we are facing a dependency issue with the code, and I believe the best course of action is to revert back a few commits on the main branch. After that, we can add the contributors back, which should allow us to merge your pull request. If we don't address this issue now, it could become more complicated to solve later. I want to keep you updated on the progress, and I will let you know if we need another pull request. I have already reverted the main branch to a working version that should deploy fine. Thank you for your understanding and patience.

**Comment by Rockleemode** [comment]
@XanderRubio okay thank you, so I will need to clone the repo again for the stable version when you're done right?

**Comment by XanderRubio** [comment]
> @XanderRubio okay thank you, so I will need to clone the repo again for the stable version when you're done right?

Hi @Rockleemode at the moment I created the stable version on another branch and attempted to merge onto the main and I'm still getting an error when deploying because of dependencies. Can you do me a favor and reclone the repo onto your VSCode and run 'npm i'? I want to see if your getting the same error as me with dependencies. Thanks @Rockleemode

**Review by XanderRubio — APPROVED** [review]
Thank you, @Rockleemode, for taking the time to share your "before I die" statement. Your ambition to become a top developer through discipline and hard work is truly admirable. I wish you all the best in your pursuit.

I apologize for the delay in merging your contribution. I have reviewed your text and image and they look great on the preview link. I will proceed with merging now.

Normally, the merging process in this repository is smooth and efficient. However, during the merging of several pull requests in a short period of time, I missed a change in the repository's package-lock.json file. This caused a delay in the deployment of the repository for about a day. I sincerely appreciate contributors like you for your patience and assistance.

This experience serves as a reminder that none of us can know everything. Collaboration and seeking help from others are crucial in the open-source community. I hope you continue your journey in open-source with a spirit of collaboration and openness to asking for help.

Your contribution will be merged successfully. Thank you again for your valuable contribution.

**Comment by XanderRubio** [comment]
@Rockleemode  Your pull request has been successfully merged!!! Congratulations Bottle with Popping CorkBottle with Popping CorkBottle with Popping CorkDouble Exclamation MarkDouble Exclamation MarkDouble Exclamation Mark. Keep it going with discipline and make it happen to be the top developer that you want to be!

 If you haven't already, please go ahead and star Glowing StarGlowing StarGlowing Starthis repo and you are more than welcome to continually contribute to this project by assisting with our [open issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues), or adding your own new open issues, and additionally you can get an idea of ideas we have to continually grow this project further as technology and tech stack continually evolve by looking at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) for the project. Have a great day, and thank you for taking the time to contribute, 
Rock! You can view your contribution now on the [live link](https://before-i-die-achievements.vercel.app/). Have a great rest of your day, and I will be sending you an invite to be a member of the Before I Die Code now.

**Comment by Rockleemode** [comment]
@XanderRubio thank you very much for the opportunity, and sorry for the late respond i've been quite busy👍

**Comment by XanderRubio** [comment]
> @XanderRubio thank you very much for the opportunity, and sorry for the late respond i've been quite busy👍

Excellent @Rockleemode and my pleasure!

**Pull request merged**
