### PR TITLE
DOCS: Added New Translations and my BID

### PR DESCRIPTION
**Pull request by MeetThakur**
## Issue Addressed
Closes  #98 

## Proposed Changes and Benefits

Added all remaining translations for "Before I Die" and added myself to contributer.md

### Checklist

- [ ✅] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [ ✅] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [ ✅] I have listed my proposed changes and their benefits.
- [✅ ] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Comment by XanderRubio** [comment]
Hi @VoidyCodes, was there a reason you closed this pull request?

**Comment by MeetThakur** [comment]
@XanderRubio Yes, I added a extra Image and wanted to change the avatar too so I closed this request.

**Comment by XanderRubio** [comment]
> @XanderRubio Yes, I added a extra Image and wanted to change the avatar too so I closed this request.

I understand. To save yourself extra work in the future, you can add your changes to the same branch and follow the normal process of using `git add`, `git commit`, and `git push`. Your new commits will then be incorporated into the current pull request you have open. This is a common practice when using Git and GitHub. Does this make sense to you?

**Comment by MeetThakur** [comment]
Oh I didn't knew that, Thank you for telling me I'll keep that in mind from now on. I have a lot to learn I guess.

**Comment by XanderRubio** [comment]
> Oh I didn't knew that, Thank you for telling me I'll keep that in mind from now on. I have a lot to learn I guess.

Of course😇. We all have lots to learn as the longer we live, the more we realize we know even less, and always new ways to improve. This is true in development and also in life.

**Pull request closed without merging**
