### PR TITLE
Add Yash jain to Before I Die

### LINKED ISSUE #188: Make your mark: Contribute to our project and help us create a platform for documenting life goals and aspirations!
Bellhop BellWe need more contributors to add their information to the JSON file and include two images that will then be seen on the Before I Die Code image gallery on the website. To contribute and start, first read the [README](https://github.com/BeforeIDieCode/BeforeIDieAchievements#readmel) and then begin following along on our [CONTRIBUTIONS-GUIDELINES](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md) file. Let's get after itMechanical Arm!!!!

It is a mistake for this issue to ever be closed. Since we are collecting contributor's text and images of what they want to do before they die. This is a continually ongoing issue and should always be open.

All successful merges receive an invite to join the [Before I Die Community](https://github.com/BeforeIDieCode).

### PR DESCRIPTION
**Pull request by yashj09**
Adding Yash Jain to the Before I Die wall

### CODE REVIEW

**Comment by yashj09** [comment]
hey , @XanderRubio  can you review my PR i have created it have some branch conflict i don't know how to resolve it #200

**Comment by XanderRubio** [comment]
Hi @yashj09! I'm currently traveling and once settled into my next location I will review your contribution! Thank you for your time in contributing and I'm looking forward to reviewing. Have a nice day!

**Review by XanderRubio — APPROVED** [review]
Hello @yashj09,

I want to thank you for taking the time to contribute to our project on what you want to do before you die, by providing text and image. Your input looks great on the preview deployment link. I will proceed to merge it now. I also wanted to inform you that I have added your details to the CONTRIBUTORS.md file, and made some minor changes to your name and the area of India where you live in the JSON data, for appearance purposes. Your work is greatly appreciated. I will resolve any merge conflicts before merging.

**Comment by XanderRubio** [comment]
@yashj09  Your pull request has been successfully merged!!! Congratulations Bottle with Popping CorkBottle with Popping CorkBottle with Popping CorkDouble Exclamation MarkDouble Exclamation MarkDouble Exclamation Mark.

 If you haven't already, please go ahead and star Glowing StarGlowing StarGlowing Starthis repo and you are more than welcome to continually contribute to this project by assisting with our [open issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues), or adding your own new open issues, and additionally you can get an idea of ideas we have to continually grow this project further as technology and tech stack continually evolve by looking at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) for the project. Have a great day, and thank you for taking the time to contribute, 
Yash! You can view your contribution now on the [live link](https://before-i-die-achievements.vercel.app/). Have a great rest of your day, and I will be sending you an invite to be a member of the Before I Die Code now.

**Pull request merged**
