### PR TITLE
Feature 48

### LINKED ISSUE #48: 🟢 🎨 UI Design for the text box that displays contributors text
**Problem**:

Great feedback from the contributor @ccelest1 on how the rainbow text background can be distracting. It would be ideal if either people decide what color they can have for the background of the text or if it can be changed to a more neutral and pleasing color scheme. After thinking of this more, it would be ideal for theming the text box after the [Before I Die Wall Project](https://beforeidieproject.com/story/). 

This requires UI research to see what displays are best, in addition to considering changing the use of the emojis. It could be better suited from a design view only to have the text "Before I Die..." and the contributors before I die text. This project can be modeled after the [Before I Die Wall Project](https://beforeidieproject.com/story/), where the textbox is of a similar black wall chalkboard with the following image and the idea of using various different randomized chalk text color for contributors' text they share for what they want to do before they die. Additionally, another thought is to customize the "Before I Die" bold text that is found in the CSS on line 165 of the [MasonryBox.module.css](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/src/Components/MasonryLayout/MasonryBox/MasonryBox.module.css ) and have that automatically be displayed and translated to a different language depending on where the contributor is contributing from. This would be another issue to create.

### Please work on the branch [feature-48](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/feature-48) for this issue.

Image of what a Before I Die Wall looks like ⬇️
Screenshot 2023-08-31 at 01 13 45

For more ideas, view the [Beofore I Die Toolkit](https://app.gumroad.com/d/3a1b28cafafadd95067dc6188ced0397) material below ⬇️
[Before I Die Guide.pdf](https://github.com/BeforeIDieCode/BeforeIDieAchievements/files/12480770/Before.I.Die.Guide.pdf)
[Before I Die column.pdf](https://github.com/BeforeIDieCode/BeforeIDieAchievements/files/12480774/Before.I.Die.column.pdf)
[Before I Die large title.pdf](https://github.com/BeforeIDieCode/BeforeIDieAchievements/files/12480775/Before.I.Die.large.title.pdf)

Current layout ⬇️

Screenshot 2023-08-30 at 23 27 28

**Resources for ideas** 📚:

- [Chalkboard Repo](https://github.com/0xmmo/chalkboard) potential idea 

- Check out the [codepen for this repo](https://codepen.io/mmoustafa/pen/AXprLM) as the background of the chalkboard could be good to use for the text box instead of the blue and yellow rainbow box 

Screenshot 2023-08-30 at 23 55 04

### PR DESCRIPTION
**Pull request by XanderRubio**
@negar-75 added code from pull request #52 to enhance the UI

### CODE REVIEW

**Review by XanderRubio — COMMENTED** [review]
File changes and additions of code is thanks to the contributor @negar-75 for enhancing the UI!

**Comment by XanderRubio** [comment]
This pull request successfully closes issue #48, and thank you to contributor @negar-75 for her pull request #52 and adding UI enhancement.

**Comment by negar-75** [comment]
so now everything has been solved?

**Comment by negar-75** [comment]
this is my first time working with Git and Git flow and that was hard experience 😂😂😂😂😂

**Comment by XanderRubio** [comment]
> so now everything has been solved?

Yes, it has! Please look at the [live link for the website](https://before-i-die-achievements.vercel.app/) for proof.

**Comment by negar-75** [comment]
although I have no idea about what just happened , but that was practical experience 😂😂😂

**Comment by negar-75** [comment]
I see!! amazing😍😍😍😍

**Comment by negar-75** [comment]
I am so ready to make another change !!!😍😍😍😍
and learn more and more about Git flow

**Comment by XanderRubio** [comment]
> I see!! amazing😍😍😍😍

Congratulations on gaining more experience with Git today than you might have thought possible when starting out. I will do my best to provide a brief description of what happened. The main issue we encountered was that your forked version and add features branch of issue-#48 hadn't been fetched to be udaped with the main working branch of the Before I Die Code repo. This was a valuable lesson for me, and we will need to have proper documentation in place to make it easier for other developers to understand and receive support on how to prevent merge conflicts from happening. If conflicts do occur, the only option is to merge the main branch into the feature branch, potentially losing the work that you want to add to the main branch and needing to revert the commit. I need to understand why this is occurring. Please let me know if you have any further questions. I will be signing off for tonight, but I would like to hear your thoughts on how we can continue to improve the UI to look more professional and sleek. Have a good night and thank you for your time and patience! I will be adding a LinkedIn recommendation later as well. Clapping HandsClapping HandsClapping HandsClapping Hands

**Comment by negar-75** [comment]
thanks @XanderRubio  for your informative text and I appreciate it,
Now I am going to create another merge request for auto translation

**Comment by XanderRubio** [comment]
> thanks @XanderRubio for your informative text and I appreciate it, Now I am going to create another merge request for auto translation

Great @negar-75 and my pleasure!

**Pull request merged**
