### PR TITLE
Add translation section to README with flag emojis (#38)

### LINKED ISSUE #38: 🟢 Add translation section to all README file languages with flag emojis
Currently working on having this Documentation translated into five other languages. **We would like to see it added to the top portion of the README, as seen in the following photo.**
Screenshot 2023-08-24 at 23 18 47

### Please add all the following flags to be displayed on all translated README files in the six different languages, and all of the flags are hyperlinked to direct to there appropriate README files.

- [x] Arabic: 🇸🇦🇦🇪 (Saudi Arabia and United Arab Emirates) Does it make sense to use these flags to represent the Arabic language?
- [x] French: 🇫🇷 (France)
- [x] Spanish: 🇪🇸 (Spain)
- [x] Chinese: 🇨🇳 (China)
- [x] Hindi: 🇮🇳 (India)

Add the five language flags for the following on the ReadMe with text and anchor text to link that says, "[Read this in other languages](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/translations/Translations.md)." This text will link to [Translations.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/translations/Translations.md) that will be modeled simiraly to this [image below⬇️](https://github.com/firstcontributions/first-contributions/blob/main/translations/Translations.md)
Screenshot 2023-08-24 at 22 34 15

**Additionally, there exits open source projects of countries flags that can be used, for example [FlagKit](https://github.com/madebybowtie/FlagKit), [country-flags](https://github.com/hampusborgos/country-flags), and [circle flags](https://github.com/HatScripts/circle-flags). The circle flag design comes across as unique and I would be in favor of this look.**

### This is modeled after the [first-contributions](https://github.com/firstcontributions/first-contributions) repository ⬇️

Screenshot 2023-08-24 at 22 34 02

### PR DESCRIPTION
**Pull request by luc881**
**Details:**
In this pull request, I've addressed issue #38 by adding a translation section to the README. To enhance the user experience, I've incorporated flag images to represent different language options. The flag images have been sourced from the "country-flags" and "circle-flags" repositories.

**Resources Used:**
- "country-flags" repository: [Link](https://github.com/hampusborgos/country-flags)
- "circle-flags" repository: [Link](https://github.com/HatScripts/circle-flags)

Fixes #38

### CODE REVIEW

**Comment by XanderRubio** [comment]
Hola Luciano! 

Thank you for taking the time to add the flags. I'll be reviewing now and making the merge shortly. I was traveling the past several days and back to my home base and will be quick to respond. I like your updated GitHub profile README file with the computer screen gif and Backend Developer title!

**Review by XanderRubio — APPROVED** [review]
Hi @luc881, great job! I really appreciate the addition of the circle flags to the README and the translations page. Thank you for taking the time to do that. We will continue to work on this project day by day and week by week. I was wondering if you could give me your opinion on whether it makes sense to display all the flags on each translated README file. For example, if the main README file is in English, a flag representing the language would be displayed, so that when someone views the Spanish version of the README, they can easily click on the English flag to view the translation. This is a minor detail, but it came to mind and I wanted to get your thoughts. The same would apply to the Translations.md file, where we would add a flag to represent the English language that has been translated. Thank you again and have a great day, Luciano!

**Comment by XanderRubio** [comment]
Merging this pull request to close out issue #38

**Comment by luc881** [comment]
Hi @XanderRubio, thank you for your feedback. I believe it would be helpful to add the flags to all the README files. Should I include them in all the README files or just in the Spanish one?🤔 Have a nice day.

**Comment by XanderRubio** [comment]
This makes sense, and thank you, Luciano, for your feedback. I will go ahead and reopen this issue #38 and edit the instructions for record purposes to have all the flags to all the README files linked to appropriate README files for translation. In addition, I will assign this issue to you😉. Thank you Luciano and please let me know if you have more thoughts to add value.

**Pull request merged**
