### PR TITLE
Add Awonuga-Oluwapelumi to Before I Die

### PR DESCRIPTION
**Pull request by Dunni0**
### Checklist

- [x] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [x] I have listed my proposed changes and their benefits.
- [x] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Review by XanderRubio — CHANGES_REQUESTED** [review]
Hi @Dunni0 

Thank you for taking the time to contribute your before I die statement! Much appreciated, and  I am very thankful for your time in contributing. Please have two different images when viewing your contribution on the [preview deployment](https://vercel.live/open-feedback/before-i-die-achievements-git-fork-dun-3a2f77-before-i-die-code.vercel.app?via=pr-comment-visit-preview-link&passThrough=1). Currently, you have your GitHub avatar image as the same as your bid_image. Once you have selected a new bid_image, I will then go ahead and merge. Let me know if you have any questions.

Xander

**Comment by Dunni0** [comment]
Hi @XanderRubio, 
I’ll fix it and revert.
Thank you!

**Comment by XanderRubio** [comment]
Excellent! Looking forward to seeing and very grateful for your time.

**Review by XanderRubio — APPROVED** [review]

**Comment by XanderRubio** [comment]
Excellent @Dunni0! Your new image looks great on the preview link, and thank you for taking the extra time to change it. Going ahead with merging now.

**Comment by XanderRubio** [comment]
@Dunni0   Your pull request has been successfully merged!!! Congratulations Bottle with Popping CorkBottle with Popping CorkBottle with Popping CorkDouble Exclamation MarkDouble Exclamation MarkDouble Exclamation Mark. 


 If you haven't already, please go ahead and star Glowing StarGlowing StarGlowing Starthis repo and you are more than welcome to continually contribute to this project by assisting with our [open issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues), or adding your own new open issues, and additionally you can get an idea of ideas we have to continually grow this project further as technology and tech stack continually evolve by looking at the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) for the project. Have a great day, and thank you for taking the time to contribute, 
Awonuga! You can view your contribution now on the [live link](https://before-i-die-achievements.vercel.app/). Have a great rest of your day, and I will be sending you an invite to be a member of the Before I Die Code now.

**Pull request merged**
