### PR TITLE
Add Angel Soto to Befor I Die

### PR DESCRIPTION
**Pull request by Angeltheesoto**
I am adding Angel Soto to Before I Die with Images and Text.

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
@Angeltheesoto All of your added changes look great on the site and will be going ahead with merging!

**Comment by XanderRubio** [comment]
Hi @Angeltheesoto, Thank you for taking the time to add your before I die statement of wanting to learn a new language and travel the world. From experience learning another language and traveling greatly adds to life experiences and a deeper updating of others and life perspectives. You will make it happen! I see you are in Brandon, Florida, and I'm a bit familiar with the area as I used to live in Orlando, Florida, and I'm well familiar with hurricanes and humid weather. 

I had to update the file path name of your JSON avatar value as the filename for your Avatar was saved with jpg.jpg. All is good, and we will change the naming to the correct format for simplicity. 

Congratulations on your pull request being merged!!!!!! Bottle with Popping CorkBottle with Popping CorkBottle with Popping Cork

If you haven't already, be sure to star  Star the repo, and additionally, like you have already, please check out the [open issue](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues) to further assist in contributions and growing the Before I Die Code. You are more than welcome to add your own open issues that you see can be of value to the project. Additionally, check out the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) to get ideas of what we have for the future features for the project to continually evolve and grow in value for developers. Have a great day, and thank you for contributing! 

Xander

**Comment by Angeltheesoto** [comment]
> Hi @Angeltheesoto, Thank you for taking the time to add your before I die statement of wanting to learn a new language and travel the world. From experience learning another language and traveling greatly adds to life experiences and a deeper updating of others and life perspectives. You will make it happen! I see you are in Brandon, Florida, and I'm a bit familiar with the area as I used to live in Orlando, Florida, and I'm well familiar with hurricanes and humid weather.
> 
> I had to update the file path name of your JSON avatar value as the filename for your Avatar was saved with jpg.jpg. All is good, and we will change the naming to the correct format for simplicity.
> 
> Congratulations on your pull request being merged!!!!!! Bottle with Popping CorkBottle with Popping CorkBottle with Popping Cork
> 
> If you haven't already, be sure to star Star the repo, and additionally, like you have already, please check out the [open issue](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues) to further assist in contributions and growing the Before I Die Code. You are more than welcome to add your own open issues that you see can be of value to the project. Additionally, check out the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) to get ideas of what we have for the future features for the project to continually evolve and grow in value for developers. Have a great day, and thank you for contributing!
> 
> Xander

Thank you @XanderRubio for the words of encouragement and personal experience, It makes me feel even more determined  to make it happen. And that's really cool, because I also have a lot of family in Orlando.

Thank you for fixing the JSON file, and I will be sure to star the repo. I really would like to contribute more and thank you for giving me guidance on how to do that.  -Angel

**Comment by XanderRubio** [comment]
> > Hi @Angeltheesoto, Thank you for taking the time to add your before I die statement of wanting to learn a new language and travel the world. From experience learning another language and traveling greatly adds to life experiences and a deeper updating of others and life perspectives. You will make it happen! I see you are in Brandon, Florida, and I'm a bit familiar with the area as I used to live in Orlando, Florida, and I'm well familiar with hurricanes and humid weather.
> > I had to update the file path name of your JSON avatar value as the filename for your Avatar was saved with jpg.jpg. All is good, and we will change the naming to the correct format for simplicity.
> > Congratulations on your pull request being merged!!!!!! Bottle with Popping CorkBottle with Popping CorkBottle with Popping Cork
> > If you haven't already, be sure to star Star the repo, and additionally, like you have already, please check out the [open issue](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues) to further assist in contributions and growing the Before I Die Code. You are more than welcome to add your own open issues that you see can be of value to the project. Additionally, check out the [ROADMAP](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/ROADMAP.md) to get ideas of what we have for the future features for the project to continually evolve and grow in value for developers. Have a great day, and thank you for contributing!
> > Xander
> 
> Thank you @XanderRubio for the words of encouragement and personal experience, It makes me feel even more determined to make it happen. And that's really cool, because I also have a lot of family in Orlando.
> 
> Thank you for fixing the JSON file, and I will be sure to star the repo. I really would like to contribute more and thank you for giving me guidance on how to do that. -Angel

I resided most of my time in Crane's Roost Park, located near Altamonte Springs. It was a pleasure, @Angeltheesoto Angel. Our goal is to advance this initiative to better aid those who wish to improve their abilities in engaging in an open project with the open source community. I hope you will continue to contribute whenever feasible, and we will strive to create open issues. Furthermore, we need to establish a community infrastructure to facilitate more communication among contributors who are keen on contributing and exchanging ideas, as well as taking action on sharing and growing their abilities as technology progresses in the process of growing this project.

**Pull request merged**
