### PR TITLE
moved upward github section

### LINKED ISSUE #190: [Feature Request] Move a section of the header to improve UI
### Description

Please level out the below section so that the `Contributors Map` at the bottom of the button lines up with the bottom of the [dummy_image](https://github.com/BeforeIDieCode/BeforeIDieAchievements/tree/main/public/img/dummy_image) box. Please see the below image. 

### Screenshots

Screenshot 2023-10-12 at 16 46 01

### Checklist

- [X] I have checked for duplicate [issues](https://github.com/BeforeIDieCode/BeforeIDieAchievements/issues)
- [X] I have read the [Contribution Guidelines]((https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md))
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by yashj09**
Closes #190 opened by @XanderRubio 
 Alinged the Github_section with the image on the left side of header

Screenshot 2023-10-12 222156

- [✔️] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [✔️ ] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [✔️ ] I have listed my proposed changes and their benefits.
- [ ✔️] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
Well done and thank you, @yashj09! Going ahead with merging now.

**Comment by XanderRubio** [comment]
@yashj09 Congrats on your pull request being merged and I recommend you now contribute to issue #188 and add your text and image to represent what you want to do before you die. Thank you for taking the time to assist and continually grow this project. Have a nice day!

**Comment by yashj09** [comment]
hey @XanderRubio can you add "HACKTOBERFEST-ACCEPTED" label to this PR

**Comment by XanderRubio** [comment]
Hi @yashj09 ! I'm currently traveling and once settled into my next location I will add the label to your pull request. Thank you for your time!

**Pull request merged**
