### PR TITLE
Fix: Issue #77, Automatically Centered Contributer's Text

### PR DESCRIPTION
**Pull request by Angeltheesoto**
I'm sorry that it looks like a lot changed but its mostly just empty spaces and VsCode auto formatting the code. The only change I  made was adding a style tag that automatically center contributer's text that are fifty or less characters long. I also noticed that I could of simply changed the width to equal 100% but I wasn't sure to do that, as that wouldn't have gone with the explained solution you asked in the issue.

### CODE REVIEW

**Comment by XanderRubio** [comment]
> I'm sorry that it looks like a lot changed but its mostly just empty spaces and VsCode auto formatting the code. The only change I made was adding a style tag that automatically center contributer's text that are fifty or less characters long. I also noticed that I could of simply changed the width to equal 100% but I wasn't sure to do that, as that wouldn't have gone with the explained solution you asked in the issue.

Hi @Angeltheesoto,

I am currently reviewing your pull request, but I have noticed that another contributor had submitted a pull request before you on the same issue of centering the text. I apologize for not being quick enough in assigning a contributor for issue #77. I will review their pull request first and provide you with an update as soon as possible.

**Review by XanderRubio — APPROVED** [review]
Great job, @Angeltheesoto! Excellent work! I noticed that you have implemented a line of code using a ternary operator to evaluate the length of userText. If the length is 50 characters or less, the inline style { width: "100%" } is applied, setting the element's width to 100%. If the condition is not met, no inline style is applied (indicated by your null). This creates more dynamic styling based on the userText length. Your contribution leads to a better user interface. Don't forget to check out the [live link](https://before-i-die-achievements.vercel.app/),as I merged more pull requests from other contributors working on UI improvements. Have a great day!

**Comment by XanderRubio** [comment]
This pull request successfully closes out issue #77. Congratulations @Angeltheesoto for your pull request merged into the main branch Clapping Hands

**Comment by XanderRubio** [comment]
AlienIn the future, to prevent multiple contributors from working on the same open issue, please ensure that you have been assigned to the issue before starting work on it. Thank you, @Angeltheesoto!

**Comment by Angeltheesoto** [comment]
Thank you @XanderRubio, I'll make sure to ask to be assigned next time. 🙏

**Comment by XanderRubio** [comment]
> Thank you @XanderRubio, I'll make sure to ask to be assigned next time. 🙏

Thak you Angel!

**Pull request merged**
