### PR TITLE
DOCS: translate CODE_OF_CONDUCT.md to hindi

### PR DESCRIPTION
**Pull request by SykikXO**
translate CODE_OF_CONDUCT.md to hindi

Closes [2nd of 5] #30

## Issue Addressed

Closes [2nd of 5] #30

## Proposed Changes and Benefits

Added Hindi translation of CODE_OF_CONDUCT.md .

### Checklist

- [x] I have thoroughly read and understand [The Contribution Guidelines](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md).
- [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior.
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc.
  - `Fix` - bug fixes.
  - `Docs` - fixing typos and adding new content.
- [x] I have listed my proposed changes and their benefits.
- [x] I have linked the corresponding issue in the Issues section.

### CODE REVIEW

**Review by XanderRubio — APPROVED** [review]
Hi @SykikXO! Excellent and thank you for taking the time to translate to Hindi the CODE_OF_CONDUCT.md👏🏻

**Comment by XanderRubio** [comment]
Thank you for your time @SykikXO and I have successfully merged, and I would encourage you to add your image and text for what you want to do before you die by working through the [CONTRIBUTION-GUIDELINES.md](https://github.com/BeforeIDieCode/BeforeIDieAchievements/blob/main/CONTRIBUTION-GUIDELINES.md). Have a nice day!

**Comment by SykikXO** [comment]
I'm really sorry for the late response. I'm glad to hear that you've successfully merged the PR. As for the contribution, I am looking forward to do it soon. Thankyou!!

**Comment by XanderRubio** [comment]
> I'm really sorry for the late response. I'm glad to hear that you've successfully merged the PR. As for the contribution, I am looking forward to do it soon. Thankyou!!

Excellent @SykikXO and no worries! Thank you for assisting and transitioning the Hindi to be now fully complete. I look forward to seeing your future contribution.

**Pull request merged**
