### PR TITLE
Add Ma'aruf Muhammad to Before I Die

### PR DESCRIPTION
**Pull request by Rockleemode**
I am adding Ma'aruf Muhammad to Before I Die with images and text

### CODE REVIEW

**Comment by XanderRubio** [comment]
> I am adding Ma'aruf Muhammad to Before I Die with images and text

Hi @Rockleemode,

Thank you for taking the time to contribute and share your aspirations on what you would like to do before you pass away. I kindly request you to run your React localhost on your local server to see your contributions working. Currently, we are encountering an error with the preview deployment that is related to the React version being used. To make this process smoother, please go through your code again, ensure that you can see your code working on your development server, and then recommit. I may have to go through the code manually to avoid the error of dependencies being shown in the terminal. I will merge your code as soon as possible. However, if you could assist me by running your code on your local server and recommitting it within the next ten hours, it would be greatly appreciated as it will save me time when reviewing. Thank you, @Rockleemode, and have a great day!

Xander

**Comment by Rockleemode** [comment]
sure thing!

**Comment by Rockleemode** [comment]
@XanderRubio I have ran the project and its working just fine with my contribution included and I have made another commit, should I push the code again even though I did not make any changes?

**Comment by XanderRubio** [comment]
> Details

Yes, please go ahead @Rockleemode. Thank you for your patience, and I apologies for having to ask. I think after several pull requests we merged, it might have changed the package.json file recently from the main, and this is causing an issue when deploying from new contributors as I'm now seeing the same issue from another pull request and will need to dive further into the issue. For now, recommit and we will see if this possibly helps with the preview deployment. Thank you!

**Pull request merged**
